# Generated by Django 3.2.8 on 2021-10-09 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 10, 9, 41, 59, 211608)),
        ),
    ]
