# Generated by Django 3.2.8 on 2021-10-11 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_reservation_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 11, 27, 4, 495888)),
        ),
    ]
