# Generated by Django 3.2.8 on 2021-10-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_reservation_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroomtype',
            name='person_cap',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='no_of_guests',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_type',
            field=models.CharField(choices=[(1, 'CASH'), (2, 'NET_BANKING'), (3, 'CHECK'), (4, 'CREDIT/DEBIT_CARD')], max_length=100),
        ),
    ]
