# Generated by Django 3.2.8 on 2021-10-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20211012_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='charge',
            field=models.CharField(default=1000, max_length=100),
            preserve_default=False,
        ),
    ]
